server:
  port: 8080

spring:
  application:
    name: bmad-edge-gateway
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bmad_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  # Web Jackson DateTime Formatting
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
